### ISSUE TITLE
Math 3D install error

### ISSUE THREAD

**Issue by doug719** [Cuis-Smalltalk/Numerics#1]
Using Cuis5.0-3866.  Math 3D from github has a date of 9/29/2019.  Using Windows 10.
Get install error:

Error: subscript is out of bounds: 1
Float32Matrix3x3(Object)>>error
Float32Matrix3x3(Object)>>errorSubscriptBounds:
Float32Matrix3x3(Object)>>basicAt:put:
Float32Matrix3x3(FloatArray)>>at:put:

**Comment by jvuletich** [comment]
Thanks for the report, Doug. The problem was attempting to install the current version of the package in a slightly outdated image (for not installing the latest updates). The fix was to update the images at the repo, which I just did.
